version: '3.8'

services:
  asistente-webapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: asistente-backend
    ports:
      - "8080:5000"
    networks:
      - chroma-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
    restart: unless-stopped

networks:
  chroma-net:
    external: true
